# Add variables that we wish to make available to soong here.
ifneq (,$(wildcard $(OUT_DIR)/.path_interposer_origpath))
ORIG_PATH := $(shell cat $(OUT_DIR)/.path_interposer_origpath)
endif
EXPORT_TO_SOONG := \
    KERNEL_ARCH \
    KERNEL_CC \
    KERNEL_CLANG_TRIPLE \
    KERNEL_CROSS_COMPILE \
    KERNEL_MAKE_FLAGS \
    TARGET_KERNEL_CONFIG \
    TARGET_KERNEL_SOURCE \
    ORIG_PATH

# Setup SOONG_CONFIG_* vars to export the vars listed above.
# Documentation here:
# https://github.com/LineageOS/android_build_soong/commit/8328367c44085b948c003116c0ed74a047237a69

SOONG_CONFIG_NAMESPACES += statixVarsPlugin

SOONG_CONFIG_statixVarsPlugin :=

define addVar
  SOONG_CONFIG_statixVarsPlugin += $(1)
  SOONG_CONFIG_statixVarsPlugin_$(1) := $$(subst ",\",$$($1))
endef

$(foreach v,$(EXPORT_TO_SOONG),$(eval $(call addVar,$(v))))

SOONG_CONFIG_NAMESPACES += STATIX
SOONG_CONFIG_STATIX += \
    ADDITIONAL_GRALLOC_10_USAGE_BITS \
    BOOTLOADER_MESSAGE_OFFSET \
    QCOM_SOONG_NAMESPACE \
    RECOVERY_SKIP_EV_REL_INPUT \
    SHOULD_WAIT_FOR_QSEE \
    SUPPORTS_EXTENDED_COMPRESS_FORMAT \
    TARGET_INIT_VENDOR_LIB \
    TARGET_LD_SHIM_LIBS \
    TARGET_SURFACEFLINGER_FOD_LIB \
    USES_QCOM_BSP_LEGACY \
    USES_QTI_CAMERA_DEVICE

SOONG_CONFIG_STATIX_ADDITIONAL_GRALLOC_10_USAGE_BITS := $(TARGET_ADDITIONAL_GRALLOC_10_USAGE_BITS)
SOONG_CONFIG_STATIX_BOOTLOADER_MESSAGE_OFFSET := $(BOOTLOADER_MESSAGE_OFFSET)
SOONG_CONFIG_STATIX_QCOM_SOONG_NAMESPACE := $(QCOM_SOONG_NAMESPACE)
SOONG_CONFIG_STATIX_RECOVERY_SKIP_EV_REL_INPUT := $(TARGET_RECOVERY_SKIP_EV_REL_INPUT)
SOONG_CONFIG_STATIX_SHOULD_WAIT_FOR_QSEE := $(TARGET_KEYMASTER_WAIT_FOR_QSEE)
SOONG_CONFIG_STATIX_SUPPORTS_EXTENDED_COMPRESS_FORMAT := $(AUDIO_FEATURE_ENABLED_EXTENDED_COMPRESS_FORMAT)
SOONG_CONFIG_STATIX_TARGET_INIT_VENDOR_LIB := $(TARGET_INIT_VENDOR_LIB)
SOONG_CONFIG_STATIX_TARGET_LD_SHIM_LIBS := $(TARGET_LD_SHIM_LIBS)
SOONG_CONFIG_STATIX_TARGET_SURFACEFLINGER_FOD_LIB := $(TARGET_SURFACEFLINGER_FOD_LIB)
SOONG_CONFIG_STATIX_USES_QCOM_BSP_LEGACY := $(TARGET_USES_QCOM_BSP_LEGACY)
SOONG_CONFIG_STATIX_USES_QTI_CAMERA_DEVICE := $(TARGET_USES_QTI_CAMERA_DEVICE)
